### ISSUE TITLE
should probably blank out the credentials in the screenshot

### ISSUE THREAD

**Issue by boxcarton** [IBM/watson-conversation-slots-intro#18]

**Comment by scottdangelo** [comment]
I actually created a credential called "fake_credential", and then deleted it. Assuming Bluemix creates unique IDs, it should never be valid again.
I could go either way, and would blank this out if others felt strongly about it. But showing an almost certainly invalid credential seems OK, and might prevent a mistake or some confusion.

**Comment by stevemart** [comment]
i'm leaning toward agreeing with @scottdangelo here, @boxcarton if you really want this addressed we can do that, but I'm OK with keep the fake credentials in there

**Comment by boxcarton** [comment]
didn't know those are fake :) sounds good to me
