### ISSUE TITLE
wcs-conversation-service binding

### ISSUE THREAD

**Issue by boxcarton** [IBM/watson-conversation-slots-intro#24]
Got

**FAILED
Could not find service wcsi-conversation-service to bind to watson-conversation-slots-intro**

When I tried to "cf push"

Fixed it by moving it from manifest.yml, is that line necessary?

**Comment by scottdangelo** [comment]
Yes, that line is necessary for Deploy to Bluemix. I tested without it and the Deploy fails. I'll look into how to make the 'cf push' work without moving the file.

**Comment by boxcarton** [comment]
Cool thanks. I'm not attached to cf push but it'd be nice to have a simple way to deploy via command line after cloning down the repo

**Comment by rhagarty** [comment]
You can still use 'cf push', but realize that it is trying to bind to the services listed in the manifest. 

So, there are 3 ways you can get this to work.
1) remove the services listed in the manifest.
2) change the names of your bluemix services to match the names in the manifest.
3) change the names in the manifest to match the names of your bluemix services.

I prefer option 2. Changing the manifest means you have to change it again if have to pull from master for any reason (bug fix, new feature, ...).

FYI - the 'Deploy to Bluemix' button solves this issue by creating the services on the fly (with the correct names).

**Comment by boxcarton** [comment]
Thanks @rhagarty . I understand your point about Deploy to Bluemix but I think it's kind of a weird workflow. Do most developer actually deploy to Bluemix first without first cloning down the repo? I'd imagine most workflows would look like cloning down repo first, play around with the code a bit, then deploy from terminal.
