### ISSUE TITLE
Git REPOS and Issue Tracking-"Required" Error

### ISSUE THREAD

**Issue by RiyaMRoy04** [IBM/watson-conversation-slots-intro#45]
Hitting with this error while I click on **DEPLOY TO BLUEMIX** button. Am I missing something? Please help.

![screen shot 2017-10-30 at 9 38 51 am](https://user-images.githubusercontent.com/11567379/32154371-4bb171d0-bd56-11e7-9563-6b4d78670386.png)

**Comment by stevemart** [comment]
@RiyaMRoy04 yeah, i'm seeing that now, too. I think the pipeline service may have changed. cc'ing @scottdangelo as an FYI, but we'll have to chat with the pipeline folks to see if something did in fact change.

**Comment by scottdangelo** [comment]
I am also seeing this. RiyaMRoy04 if you need to deploy this code immediately, please be aware that you can follow the manual steps and you should be able to get up and running in just a few minutes.

**Comment by RiyaMRoy04** [comment]
Thanks @scottdangelo I was in between a session this morning(IST) and wanted to show it quickly. Hence, tried Deploy to Bluemix! Thanks I shall follow the manual steps and bring it up :)
