### ISSUE TITLE
old pizza order-watson conversation

### ISSUE THREAD

**Issue by vkjuju** [IBM/watson-conversation-slots-intro#74]
Hi, 
Could you share the link of "old pizza order-watson conversation", I'd like compare the difference between old and new(slots)

Thanks
Joe

**Comment by scottdangelo** [comment]
If you clone this repository:
`git clone https://github.com/IBM/watson-conversation-slots-intro`
Then you can look at the commit logs:
`git log`
You can then find the point you want to revert to, either by date or the messages in the commit.Then:
`git checkout <commit_id>`
for example:
`git checkout 1863fa1ab4697cd5e886d52410127c174f9f185f`

**Comment by vkjuju** [comment]
sorry , I don't know which one is the old one without slots version ?
commit 22d226727d9de3b0c262f81628629e325eda38ff
Merge: 9989b62 b73fc10
Author: Rich Hagarty <rich.hagarty@ibm.com>
Date:   Wed Apr 25 15:58:34 2018 -0700

    Merge pull request #70 from IBM/addPackageLock

    Add package-lock.json to repository.

commit 9989b62cda82f735766e65adbf2bd53355bb8f17
Merge: a0cc5a0 9f4351f
Author: Rich Hagarty <rich.hagarty@ibm.com>
Date:   Wed Apr 25 15:57:56 2018 -0700

    Merge pull request #71 from IBM/removeTracker

    Remove deprecated metrics-tracker.

commit b73fc10fe5ea0001ac63f606e9d138edfd72f311
Author: Scott DAngelo <scott.dangelo@gmail.com>
Date:   Wed Apr 25 16:26:34 2018 -0600

    Add package-lock.json to repository.

commit 9f4351f1b74fcc81464b26f549d0828ebd7a5807
Author: Scott DAngelo <scott.dangelo@gmail.com>
Date:   Wed Apr 25 16:23:53 2018 -0600

    Remove deprecated metrics-tracker.

**Comment by stevemart** [comment]
The oldest example of the pizza dislocated we have still uses slots unfortunate, you can check it out here https://github.com/IBM/watson-conversation-slots-intro/blob/bf71d8794a19418bdf3316f3bf04e77cdbb1de0b/data/pizza-advanced.json

**Comment by stevemart** [comment]
Scott did a short example on his blog about the differences, a full example was never created. https://developer.ibm.com/code/2017/09/19/managing-resources-efficiently-watson-conversation-slots/
