### ISSUE TITLE
How to use api_key instead of username/password with new Watson service?

### ISSUE THREAD

**Issue by mzkz917** [IBM/watson-conversation-slots-intro#75]
I tried to run the app according to the guidance(README.md) but found it in the **step 3. Get IBM Cloud service credentials and add to .env file*** that new Watson service does not show any username/password but api_key instead.
How can I complete the step 3 with new Watson service?

**Comment by scottdangelo** [comment]
We have updated this pattern and the README to [show how to use the api_key](https://github.com/IBM/watson-conversation-slots-intro#3-get-ibm-cloud-service-credentials-and-add-to-env-file). Can you please try it now?

**Comment by mzkz917** [comment]
I could see your new guidance worked well.
Thank you so much!
