### ISSUE TITLE
environment variable "service_watson_conversation" is not set for deploying to docker option

### ISSUE THREAD

**Issue by lee-zhg** [IBM/watson-conversation-slots-intro#85]
Doing the container deployment option

After the deployment, found the following error in the log. Then review the steps and did not find environment variable "service_watson_conversation" is set anywhere.

 ++ jq -r .password
++ echo ''
+ export CONVERSATION_PASSWORD=
+ CONVERSATION_PASSWORD=
++ echo ''
++ jq -r .username
+ export CONVERSATION_USERNAME=
+ CONVERSATION_USERNAME=
+ echo 'CONVERSATION_USERNAME == '
+ echo 'CONVERSATION_PASSWORD == '
+ npm start
CONVERSATION_USERNAME == 
CONVERSATION_PASSWORD == 
npm info it worked if it ends with ok
npm info using npm@5.3.0
npm info using node@v8.5.0
npm info lifecycle watson-conversation-slots-intro@0.1.1~prestart: watson-conversation-slots-intro@0.1.1
npm info lifecycle watson-conversation-slots-intro@0.1.1~start: watson-conversation-slots-intro@0.1.1
&gt; watson-conversation-slots-intro@0.1.1 start /usr/src/app
&gt; node server.js
/usr/src/app/node_modules/watson-developer-cloud/lib/base_service.js:73
      throw new Error('Argument error: username and password are required unless use_unauthenticated is set');
      ^ 
 Error: Argument error: username and password are required unless use_unauthenticated is set
    at ConversationV1.BaseService.initCredentials (/usr/src/app/node_modules/watson-developer-cloud/lib/base_service.js:73:13)
    at ConversationV1.BaseService (/usr/src/app/node_modules/watson-developer-cloud/lib/base_service.js:44:18)
    at new ConversationV1 (/usr/src/app/node_modules/watson-developer-cloud/conversation/v1.js:31:15)
    at Object.value (/usr/src/app/node_modules/watson-developer-cloud/index.js:91:14)
    at Object.&lt;anonymous&gt; (/usr/src/app/app.js:40:27)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.&lt;anonymous&gt; (/usr/src/app/server.js:22:14)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
npm info lifecycle watson-conversation-slots-intro@0.1.1~start: Failed to exec start script
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! watson-conversation-slots-intro@0.1.1 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the watson-conversation-slots-intro@0.1.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-09-07T17_53_19_988Z-debug.log

**Comment by scottdangelo** [comment]
The ENV variables are explained [here](https://github.com/IBM/watson-conversation-slots-intro/blob/master/doc/source/Container.md#look-under-the-hood).
Did you bind the service to your kubernetes cluster?

**Comment by lee-zhg** [comment]
Thanks @scottdangelo . I did bind the conversation service. But, username and password are not part of the security. When running command kubectl get secret my-secret -o yaml, it does not show

**Comment by lee-zhg** [comment]
secret

**Comment by lee-zhg** [comment]
Below are the output of command "kubectl get secret binding-lz-wcsi-conversation-service -o yaml":


leez@tivoli77:~/tmp/watson-conversation-slots-intro-master$ kubectl get secret binding-lz-wcsi-conversation-service -o yaml 

apiVersion: v1

data:

  binding: eyJ1cmwiOiJodHRwczovL2dhdGV3YXkud2F0c29ucGxhdGZvcm0ubmV0L2Fzc2lzdGFudC9hcGkiLCJ1c2VybmFtZSI6ImMyMDJhNDRiLTg3MzAtNDRmOS05NWQ5LWE2OTdmMzIyMTM1NiIsInBhc3N3b3JkIjoiY2RyVFlXSzJCckp6In0=

kind: Secret

metadata:

  annotations:

    service-instance-id: 981767f1-44f7-4f50-9c18-6833dfa249dc

    service-key-id: d68ea6bb-061c-44a6-a991-ff0277f3a403

  creationTimestamp: 2018-09-07T19:57:18Z

  name: binding-lz-wcsi-conversation-service

  namespace: default

  resourceVersion: "21417"

  selfLink: /api/v1/namespaces/default/secrets/binding-lz-wcsi-conversation-service

  uid: 39da0fba-b2d8-11e8-8c7e-9ec918701742

type: Opaque

**Comment by lee-zhg** [comment]
For some reason, I have to create my image and then deploy it. It's working now. 

Great information
